line-length = 88
target-version = "py310"

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["D203", "D213"]
fixable = "all"

[lint.per-file-ignores]
"tests/**.py" = ["S101"]

[format]
quote-style = "double"
indent-style = "space"
