system:
  version: 3.0.0
  encoding: utf-8
  debug_mode: false
  test_mode: false
paths:
  root_dir: .
  download_folder: ./downloads
  work_folder: ./data/work
  storage_folder: ./data/storage
  output_folder: ./outputs
  log_folder: ./logs
  checkpoint_folder: ./data/checkpoint
database:
  file_path: ./data/storage/ecommerce_database.xlsx
  sheet_name: Products
  backup_count: 5
  auto_save_interval: 10
web_automation:
  total_products: 30
  browser: chrome
  window_state: maximized
  zoom_level: 100
  tab_switch_delay: 0.5
  close_after_process: true
  image_matching:
    confidence: 0.8
    grayscale: true
    multi_scale:
    - 0.8
    - 0.9
    - 1.0
    - 1.1
    - 1.2
    region_limit: true
    cache_templates: true
    match_method: cv2.TM_CCOEFF_NORMED
  buttons:
    detail:
      primary: assets/img/detail_button.png
      # alternative: assets/img/detail_button_alt.png
      confidence: 0.85
      retry: 5
      wait_after: 2.0
      search_region:
      - 0
      - 200
      - 1920
      - 800
      click_offset:
      - 0
      - 0
    fireshot:
      trigger_key: ctrl+shift+s
      save_button: assets/img/fireshot_save.png
      confidence: 0.8
      timeout: 0
      pre_wait: 1.0
      wait_after: 3.0
      post_wait_timeout: 20.0
      post_wait_interval: 0.5
      post_wait_confidence: 0.7
      progress_template: assets/img/fireshot_progress.png
      progress_confidence: 0.75
      completion_template: assets/img/fireshot_done.png
      completion_confidence: 0.85
      save_tab_template: assets/img/fireshot_save_tab.png
      save_tab_confidence: 0.8
      product_tab_template: assets/img/product_tab_active.png
      product_tab_confidence: 0.85
      auto_close_tab: true
      tab_close_wait: 0.5
      tab_close_timeout: 10.0
      tab_poll_interval: 0.5
    analysis:
      confidence: 0.85
      default_retry: 8
      default_timeout: 30.0
      wait_between: 1.5
      download_timeout: 45.0
      sort_popup:
        trigger_hotkey: ctrl+shift+a
        detector: assets/img/popup_context.png
        confidence: 0.8
        timeout: 25.0
        wait_after_trigger: 0.5
      review_button:
        template: assets/img/review_button.png
        confidence: 0.85
        retry: 12
        timeout: 35.0
        wait_after: 0.5
      analysis_start:
        template: assets/img/analysis_start.png
        confidence: 0.85
        retry: 10
        timeout: 45.0
        wait_after: 1.0
      excel_download:
        template: assets/img/excel_download.png
        confidence: 0.85
        retry: 15
        timeout: 60.0
        wait_after: 1.0
      crawling_tool:
        template: assets/img/crawling_tool.png
        confidence: 0.85
        retry: 10
        timeout: 35.0
        wait_after: 1.0
      review_disappear_check:
        timeout: 15.0
        poll_interval: 0.5
    navigation:
      next_tab: ctrl+tab
      prev_tab: ctrl+shift+tab
      close_tab: ctrl+w
  scrolling:
    initial_scroll: 1
    amount: 500
    max_scrolls: 32
    wait_between: 0.5
    smooth_scroll: true
  error_handling:
    retry_attempts: 3
    retry_delay: 1.0
    fail_fast_limit: 3
    consecutive_fail_action: pause
    auto_restart_browser: true
    checkpoint_enabled: true
    checkpoint_interval: 1
    skip_list_file: ./data/skip_list.txt
ocr:
  engine: tesseract
  languages:
  - ko
  - en
  gpu: false
  regions:
    product_name:
    - 100
    - 50
    - 800
    - 150
    price:
    - 100
    - 200
    - 300
    - 250
    brand:
    - 100
    - 300
    - 500
    - 350
    description:
    - 100
    - 400
    - 1000
    - 500
  preprocessing:
    grayscale: true
    denoise: true
    threshold: 128
    dpi: 300
  tesseract:
    command: ${TESSERACT_CMD}
    psm: 3
    oem: 3
    config: --oem 3 --psm 3 -l kor+eng
  easyocr:
    detail: 1
    paragraph: true
    width_ths: 0.5
ai:
  provider: vertex
  vertex:
    project_id: jadong-471919
    location: us-central1
    credentials_path: ${VERTEX_CREDENTIALS}
    model:
      name: gemini-2.5-pro
      temperature: 0.3
      max_output_tokens: 1000
      top_p: 0.9
  generation:
    retry_attempts: 3
    timeout: 45
    exponential_backoff: true
    batch_size: 5
    max_api_calls: 30
  prompt:
    template_file: 상세페이지 기획안 작성 프롬프트 (자연어 버전).md
    tone: professional
    language: korean
    max_length: 500
    output_format: json+body
    schema:
      required:
      - product_name
      - unique_features
      - call_to_action
      optional:
      - price_mention
      - review_summary
    must_include: []
gui:
  window:
    title: Ultimate Automation System v3.0.0
    size: 1400x800
    min_size: 1200x600
    resizable: true
    theme: modern
performance:
  batch_size: 10
  memory_limit_mb: 2048
  gc_interval: 50
  parallel_ocr: true
  max_workers: 4
  cache_size_mb: 512
logging:
  level: INFO
  format: '[%(asctime)s][%(name)s][%(levelname)s] %(message)s'
  date_format: '%Y-%m-%d %H:%M:%S'
  file_rotation: daily
  max_files: 30
  max_size_mb: 100
  console_output: true
  gui_output: true
