system:
  version: "3.0.0"
  debug_mode: false
  test_mode: false

paths:
  root_dir: "."
  download_folder: "./downloads"
  log_folder: "./logs"
  output_folder: "./outputs"

ai:
  provider: "vertex"
  vertex:
    project_id: "your-project-id"
    location: "us-central1"
    credentials_path: "./config/vertex-service-account.json"
    model:
      name: "gemini-2.5-pro"
      temperature: 0.3
      max_output_tokens: 1000
      top_p: 0.9

logging:
  level: "INFO"
  format: "[%(asctime)s][%(name)s][%(levelname)s] %(message)s"
  file_rotation: "daily"